spring.application.name=flowbase
flowbase.jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXNlY3JldC10ZXN0LWtleS1mb3ItZmxvd2Jhc2UtandrLWdlbmVyYXRpb24tMTIzNDU2Nzg5MA==}
flowbase.jwt.expriationminutes=${JWT_EXPIRATION_MINUTES:60}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/flowbase}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:purushotham}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
flowbase.rate-limit.enabled=true
flowbase.rate-limit.default-capacity=10
flowbase.rate-limit.refill-rate=2
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
logging.pattern.console=%d{yyyy-MM-dd HH-mm-ss.SSS} [%thread] %-5level %logger{36} [traceId=%X{traceId}, spanId=%X{spanId}] - %msg%n
spring.jpa.open-in-view=false