CREATE TABLE IF NOT EXISTS FILE_METADATA
(
    ID
    VARCHAR
(
    64
) PRIMARY KEY,
    TENANT_ID VARCHAR
(
    64
) NOT NULL,
    UPLOADER_ID VARCHAR
(
    64
) NOT NULL,
    FILENAME VARCHAR
(
    255
) NOT NULL,
    CONTENT_TYPE VARCHAR
(
    128
) NOT NULL,
    SIZE_BYTES BIGINT NOT NULL,
    STORAGE_KEY VARCHAR
(
    512
) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
                             );

CREATE INDEX IF NOT EXISTS IDX_FILE_META_TENANT ON FILE_METADATA(TENANT_ID);