CREATE TABLE IF NOT EXISTS OUTBOX_EVENT (
    ID VARCHAR(64) PRIMARY KEY,
    TENANT_ID VARCHAR(64) NOT NULL,
    EVENT_TYPE VARCHAR(128) NOT NULL,
    PAYLOAD TEXT NOT NULL,
    STATUS VARCHAR(32) DEFAULT 'PENDING' NOT NULL,
    RETRY_COUNT INT DEFAULT 0 NOT NULL,
    MAX_RETRIES INT DEFAULT 3 NOT NULL,
    ERROR_MESSAGE TEXT,
    LEASED_UNTIL TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS IDX_OUTBOX_STATUS_LEASE ON OUTBOX_EVENT(STATUS, LEASED_UNTIL);
CREATE INDEX IF NOT EXISTS IDX_OUTBOX_TENANT ON OUTBOX_EVENT(TENANT_ID);
