ALTER TABLE COLLECTIONS
    ADD COLUMN CACHE_TTL_SECONDS BIGINT;
ALTER TABLE COLLECTIONS
    ADD COLUMN LOCK_TTL_SECONDS BIGINT;

ALTER TABLE COLLECTION_FIELDS
    ADD COLUMN SEARCHABLE BOOLEAN NOT NULL DEFAULT TRUE;

-- Update the TSV trigger function to index searchable fields dynamically (always using English vector)
CREATE
OR REPLACE FUNCTION UPDATE_DOCUMENT_TSV()
   RETURNS TRIGGER AS $$
   DECLARE
R RECORD;
       COMBINED_TEXT
TEXT := '';
BEGIN
FOR R IN
SELECT key, value
FROM JSONB_EACH_TEXT(NEW.DATA)
WHERE key IN (
    SELECT name
    FROM COLLECTION_FIELDS
    WHERE COLLECTION_ID = NEW.COLLECTION_ID
  AND SEARCHABLE = TRUE
    )
    LOOP
    IF R.value IS NOT NULL
  AND R.value <> '' THEN
    COMBINED_TEXT := COMBINED_TEXT || ' ' || R.value;
END IF;
END LOOP;

       NEW.TSV_DOCUMENT
:= TO_TSVECTOR('english', COALESCE(COMBINED_TEXT, ''));
RETURN NEW;
END;
   $$
LANGUAGE plpgsql;