CREATE TABLE JOB_DLQ (
    ID VARCHAR(36) PRIMARY KEY,
    EVENT_TYPE VARCHAR(100) NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    PAYLOAD TEXT NOT NULL,
    ERROR_MESSAGE TEXT,
    FAILED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
