CREATE TABLE TENANTS
(
    ID      VARCHAR(36) PRIMARY KEY,
    NAME    VARCHAR(100)        NOT NULL,
    API_KEY VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE USERS
(
    ID            VARCHAR(36) PRIMARY KEY,
    TENANT_ID     VARCHAR(36)  NOT NULL,
    EMAIL         VARCHAR(100) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLE          VARCHAR(50)  NOT NULL,
    CONSTRAINT fk_users_tenant FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
    UNIQUE (TENANT_ID, EMAIL)
);