CREATE TABLE COLLECTIONS
(
    ID        VARCHAR(36) PRIMARY KEY,
    TENANT_ID VARCHAR(36)  NOT NULL REFERENCES TENANTS (ID) ON DELETE CASCADE ,
    NAME      VARCHAR(100) NOT NULL,
    UNIQUE (TENANT_ID, NAME)
);

CREATE TABLE COLLECTION_FIELDS
(
    ID            VARCHAR(36) PRIMARY KEY,
    COLLECTION_ID VARCHAR(36)  NOT NULL REFERENCES COLLECTIONS (ID) ON DELETE CASCADE ,
    NAME          VARCHAR(100) NOT NULL,
    TYPE          VARCHAR(50)  NOT NULL,
    REQUIRED      BOOLEAN DEFAULT FALSE,
    UNIQUE (COLLECTION_ID, NAME)
);