CREATE TABLE COLLECTION_DOCUMENTS
(
    ID            VARCHAR(36) PRIMARY KEY,
    COLLECTION_ID VARCHAR(36)              NOT NULL REFERENCES COLLECTIONS (ID) ON DELETE CASCADE,
    DATA          JSONB                    NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (COLLECTION_ID, ID)
);