CREATE TABLE REFRESH_TOKENS
(
    TOKEN      VARCHAR(255) PRIMARY KEY,
    USER_ID    VARCHAR(255)             NOT NULL REFERENCES USERS (ID),
    TENANT_ID  VARCHAR(255)             NOT NULL REFERENCES TENANTS (ID),
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    REVOKED    BOOLEAN                  NOT NULL DEFAULT FALSE
);
