CREATE
OR REPLACE FUNCTION UPDATE_DOCUMENT_TSV()
       RETURNS TRIGGER AS $$
       DECLARE
R RECORD;
            COMBINED_TEXT
TEXT := '';
BEGIN
FOR R IN
SELECT *
FROM JSONB_EACH_TEXT(NEW.DATA) LOOP IF R.VALUE IS NOT NULL AND R.VALUE <> '' THEN
                              COMBINED_TEXT := COMBINED_TEXT || ' ' || R.VALUE;
END IF;
END LOOP;

            NEW.TSV_DOCUMENT
:= TO_TSVECTOR('english',COALESCE(COMBINED_TEXT,''));
RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER COLLECTION_DOCUMENT_TSV_UPDATE
    BEFORE INSERT OR
UPDATE ON COLLECTION_DOCUMENTS
    FOR EACH ROW EXECUTE FUNCTION UPDATE_DOCUMENT_TSV();